// react/first/src/main.js
import React from 'react';
import ReactDOM from 'react-dom';

window.addEventListener('load', main);

class Hello extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return <div>{this.props.message}</div>;
  }
}

function main() {
  window.removeEventListener('load', main);
  const root = document.getElementById('root');
  ReactDOM.render(
    <Hello message="Hello!! Kin-iro Mosaic" />,
    root
  );
}

// angular/first/src/main.ts
import { Component, NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

@Component({
  selector: 'app',
  template: '<div>{{message}}</div>'
})
class AppComponent {
  message = 'Hello!! Kin-iro Mosaic'
}

@NgModule({
  imports     : [BrowserModule],
  declarations: [AppComponent],
  bootstrap   : [AppComponent]
})
class AppModule {
}

window.addEventListener('load', main);

function main() {
  window.removeEventListener('load', main);
  platformBrowserDynamic().bootstrapModule(AppModule);
}
